      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Replace with your desired version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  
