ALIENVAULT_OTX_API_KEY = "3ea5aedf3bb93d44aa41c174b8d85ef005128c089b8b3d5139a68a745865fc89"
HACKERONE_API_KEY = "qC3G/sBzMRqfjv0NbooakKtZINWDNa1XPQ1FvzELAz4="
HF_TOKEN = "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"
